project_id = "kmejplnwnajjaxsqzmwz"

[functions.financial-assistant-gemini]
verify_jwt = true

[functions.process-scheduled-transactions]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
